### PR TITLE
fix: returns the package starts

### LINKED ISSUE #61: Package indexer does not return values for the `stars` field
The api defines a 'stars' field on the `KurtosisPackage` object (https://github.com/kurtosis-tech/kurtosis-package-indexer/blob/main/api/protobuf/kurtosis_package_indexer.proto#L37) - however the value is not populated at all in the `readPackage` or `getpackages` responses.

Please include this value in the responses.

### PR DESCRIPTION
**Pull request by leoporoli**
fix #61

### CODE REVIEW

File: server/crawler/crawler.go [hunk 1]
```diff
@@ -233,28 +235,41 @@ func (crawler *GithubCrawler) crawlKurtosisPackages(
 	return len(kurtosisPackageUpdated), len(kurtosisPackageAdded), len(kurtosisPackageRemoved), nil
 }
 
-func ReadPackage(
+func (crawler *GithubCrawler) ReadPackage(
```
Comment (adschwartz) [inline server/crawler/crawler.go:238]: @leoporoli What's the need for making this a function that depends on the crawler? We don't use the crawler in this context?

File: server/crawler/crawler.go [hunk 2]
```diff
@@ -233,28 +235,41 @@ func (crawler *GithubCrawler) crawlKurtosisPackages(
...
 	if err != nil {
 		return nil, stacktrace.Propagate(err, "An error occurred extracting content for Kurtosis package repository '%s'", packageRepositoryLocator)
 	}
 	if !packageFound {
-		logrus.Warn("No Kurtosis package found.") // don't want to log provided package repository locator bc it's a security risk (eg. malitious data)
+		logrus.Warn("No Kurtosis package found.") // don't want to log provided package repository locator bc it's a security risk (e.g. malicious data)
 		return nil, stacktrace.NewError("No Kurtosis package found. Ensure that a package exists at '%v' with valid '%v' and '%v' files.", packageRepositoryLocator, kurtosisYamlFileName, starlarkMainDotStarFileName)
 	}
 
+	// TODO try to get the repo from the store first, to improve performance
```
[the remark this answers is not in the document]
Comment (adschwartz) [reply server/crawler/crawler.go:265]: @leoporoli I don't know that we want to get the repo from the store. This function is meant to reach out to the raw content on github without using a cache

File: server/crawler/crawler.go [hunk 3]
```diff
@@ -395,7 +407,7 @@ func extractKurtosisPackageContent(
 
 	nowAsUTC := getTimeProtobufInUTC()
 
-	kurtosisYamlFilePath := fmt.Sprintf("%s%s", packageRepositoryMetadata.RootPath, packageRepositoryMetadata.KurtosisYamlFileName)
+	kurtosisYamlFilePath := fmt.Sprintf("%s/%s", packageRepositoryMetadata.RootPath, packageRepositoryMetadata.KurtosisYamlFileName)
```
Comment (adschwartz) [inline server/crawler/crawler.go:410]: @leoporoli This is surprising. i wonder how this is not causing bugs. What was the result before and after this change? It's possible we need to make a chagne in the frontend as well to handle this change?

**Review by adschwartz — COMMENTED** [review]
Hi @leoporoli . Added a couple of comments to look into

File: server/crawler/crawler.go (hunk 1 above)
Comment (leoporoli) [reply server/crawler/crawler.go:238]: Well, I did it because I was planning to use the `crawler.store` to get the repository from the store but I'll revert it now that I won't use the store here

**Review by adschwartz — APPROVED** [review]
